### ISSUE TITLE
counter spams chat input field on firefox?

### ISSUE THREAD

**Issue by xDreamCoding** [xDreamCoding/Carduinowebdroid#54]

**Comment by st0ph** [comment]
What?

**Comment by xDreamCoding** [comment]
im firefox wird irgendwas in das chat input feld geschrieben die ganze zeit irgendwelche random zahlen
war zumindest bei mir mal so weiß nicht ob das mal irgendwann gefixt wurde

**Comment by st0ph** [comment]
Fixed in some commit
